### ISSUE TITLE
[BE] 2020.05.06 팀 활동 작업 체크리스트

### ISSUE THREAD

**Issue by jypthemiracle** [codesquad-member-2020/baseball-06#11]
## 개요
* 5월 6일 BE 공동 작업시간(2시-6시)에 진행할 페어 활동 내용을 정리한 것이다.

## 체크리스트
* [x] Pitching vs Batting 코드 전 영역에서 메소드 이름과 위치 합의하고, 작업하기
* [x] Player 상위 클래스 및 하위 클래스 객체 분리하기 (제네릭 및 와일드카드 사용 여부 합의 요망)
* [x] Service 클래스(객체) 기능 분리하기 (PitchingResult, PitchingService 등)
  * [x] PlaterAppearanceService 로 분리
  * [x] InningService 로 분리
* [x] #17 json 을 이용한 표준 응답 객체 만들기 
* [ ] 한 이닝(1회 초)의 기능을 배포하기 위한 기타 비즈니스 로직 작업 의논하기
* [ ] JSON 형식 합의하고, FE/iOS와도 논의하는 기회 갖기
* [ ] AWS 배포하기

**Comment by Hyune-c** [comment]
내일 할일
- DB 구조에 대한 생각 후 공유

**Comment by Hyune-c** [comment]
> Refactoring
- [x] Delete constructor with no id
- [x] Add DevService for DevController and test
