### ISSUE TITLE
[데일리 스크럼 및 회고] 2020.05.06

### ISSUE THREAD

**Issue by jypthemiracle** [codesquad-member-2020/baseball-06#16]
## 2020년 5월 6일
* Sigrid Jin
* Dan
* Ellin
* 또치

**Comment by TTOzzi** [comment]
어제 한 일
* 게임 목록 화면 UI 구현
* 게임 진행 화면 UI 구현

오늘 할 일
* 수업듣기
* 상세 스코어 화면 UI 구현
* 백엔드분들과 API 구조에 대해 의논

**Comment by Elllin** [comment]
어제 한 일
- react Router, useReducer, hooks 공부

오늘 할 일
- 게임 선택 기능 구현
- 수업듣기

**Comment by jypthemiracle** [comment]
어제 한 일
* JSON 데이터 고민
* Dan이 올려주신 PR 리뷰하기

오늘 할 일
* BE 체크리스트에 따른 업무 수행
* 1차 배포 최대한 목표
* 수업 듣기

**Comment by Hyune-c** [comment]
어제 한 일
- PR 리뷰
오늘 할 일
- BE 체크리스트에 따른 업무 수행
