### ISSUE TITLE
2020.05.07

### ISSUE THREAD

**Issue by Hyune-c** [codesquad-member-2020/baseball-06#20]
어제 한 일  
오늘 할 일

**Comment by Hyune-c** [comment]
어제 한 일
- #11 Refactoring
  - Delete constructor with no id
  - Add DevService for DevController and test
- #18 Make ERD
오늘 할 일
- ERD 논의
- RDS 올리기 (?)

**Comment by jypthemiracle** [comment]
어제 한 일
* Dan과 함께 1차 배포

오늘 할 일
* ERD 논의
* 한 이닝 DB에 넣어두고, 이를 2차 배포

**Comment by Elllin** [comment]
어제 한 일
 - 게임 선택화면 구현
오늘 할 일
 - 게임 진행화면 구현
 - api를 이용한 서버 통신

**Comment by TTOzzi** [comment]
어제 한 일
* 상세 스코어 화면 UI 구현

오늘 할 일
* 코드 리팩토링
* API 서버 통신
