### ISSUE TITLE
[2020.05.08] 데일리 스크럼 & 회고

### ISSUE THREAD

**Issue by jypthemiracle** [codesquad-member-2020/baseball-06#33]
## 어제 한 일
* ERD 설계
* DB 설계

## 오늘 할 일
* DB 구현 완료
* DTO 생성
* 2차 배포

**Comment by jypthemiracle** [comment]
## 어제 한 일
* ERD 설계
* DB 설계

## 오늘 할 일
* DB 통신 완성
* DTO 생성
* 2차 배포

**Comment by Elllin** [comment]
## 어제 한 일
- 게임 선택 라우팅
- inningStatus view 구현

## 오늘 할 일
- 게임 진행 구현
- api 서버 통신

**Comment by TTOzzi** [comment]
## 어제 한 일
* 상세 스코어 화면 수정
* 리팩토링
## 오늘 할 일
* API 통신

**Comment by Hyune-c** [comment]
# 어제 한 일
- DB 연결
- Game, Team Table 생성 및 쿼리 테스트 (repository)
- Enum 의 세분화

# 오늘 할 일
- repository 관련 추가 구현
