### ISSUE TITLE
[2020.05.12] 데일리 스크럼 및 회고

### ISSUE THREAD

**Issue by jypthemiracle** [codesquad-member-2020/baseball-06#44]
### Sigrid
* 어제 한 일
	* Dan, Sigrid 코드 병합
	* DTO 객체 구현
	* DAO 객체 구현

* 오늘 할 일
	* 배포
	* 이닝 추가하기

**Comment by Elllin** [comment]
# 어제 한 일
 - 수업 듣기
 - 게임 진행 기능 마무리
 - 중계 영역 화면 구현

# 오늘 할 일
 - 선수 명단 화면 구현
 - 상세 점수 팝업 화면 구현
 - 라우팅 처리

**Comment by TTOzzi** [comment]
## 어제 한 일
* 게임진행화면 API 연동
* 애니메이션 구상
## 오늘 할 일
* 목업 데이터 구현
* 목업 데이터로 화면연동

**Comment by Hyune-c** [comment]
- 어제 한 일
  - Dan, Sigrid 코드 병합
  - Game 에 대해 user join 후 inning create
- 오늘 할 일
  - 이후 로직 만들기
