### ISSUE TITLE
API Return Format Consideration

### ISSUE THREAD

**Issue by jypthemiracle** [codesquad-member-2020/baseball-06#9]
## Things to consider
* batting API / pitching API가 차이가 있을까?
	* No. RESTful하다 뭐 이런 고민은 제외하고, 일단 매 배팅마다 모든 상황을 업데이트해주기 때문이다.

## 수비 및 공격 모두, 타석의 플레이를 진행하기 위한 API 모음
* tentative URL: ```ec2_address:8080/api/play```
* HTTP Method: POST

### API Format Example
* Usage of API
	* 수비: pitch 버튼을 누를 때마다 요청에 따른 응답이 온다.
	* 공격: 클라이언트가 주기적으로 요청을 보내면 응답이 온다.

### Request API Format
* JSON format
```
"proceedGame": true
```

### Response API Format
* JSON format (만약 ```proceedGame```이 ```true```인 경우)
```
{
	"status": true,
	"battingResult": "아웃", //"스트라이크", "볼", "아웃" "안타", "아웃, 공수 전환" 5가지의 경우가 있음.
}
```
* JSON Format (만약 ```proceedGame```이 ```false```인 경우)
	* 서버가 돌아가는 지 확인하기 위한 용도
```
{
	"status": true
}
```

## 현재 상황을 체크하는 API
* tentative URL: ```ec2_address:8080/api/status```
* HTTP Method: GET

```
{
"player": [ //만약 아웃이 되어서 새로운 player가 등장할 경우, 새 플레이어를 반영함.
	"currentPitcher": [
		"teamName": "SK Wyverns",
		"teamNum": 0,
		"playerName": "Dan",
		"playerNum": 1
    ],
   	"currentBatter": [
		"teamName": "Doosan Bears",
		"teamNum": 1,
		"playerName": "Sigrid",
		"playerNum": 1
    ]
],
"inningStatus": [
	"inningNum": 1,
	"inningType": 0, // "초"인 경우 0을 떨어뜨리고, "말"인 경우 1을 떨어뜨린다. 현재 플레잉하는 팀을 구별하는 용도로도 사용될 수 있다.
	"strikeCount": 1,
	"ballCount": 2,
	"outCount": 2
],
"currentBaseman": [
	"1B": [
		"playerName": "Aurora",
		"playerNum": 2
   	],
	"2B": [
		"playerName": "Amanda Tenjford",
		"playerNum": 3
   	],
	"3B": [
		"playerName": "", //현재 4루에 타자가 진출하지 않았다는 의미
		"playerNum": ""
	]
],
"currentScore":[
	"team0": 1, //key값에 대한 고민이 필요할 것 같습니다.
	"team1": 2
]
}
```

**Comment by jypthemiracle** [comment]
Request @Hyune-c 's review for this issue.

**Comment by Hyune-c** [comment]
`updatedPlayer` 에 들어가는 Player 는 기존의 객체를 재사용하면 될 것 같습니다. DTO 라고 하여 굳이 다른 형태를 만들 필요가 있을까요?

**Comment by Hyune-c** [comment]
- updatedStatus
  - inningType 을 숫자로 하는 것 보다는 명시적인 Enum 으로 내리는 건 어떨까요

**Comment by Hyune-c** [comment]
전체적으로 모호한 숫자의 사용이 있는 것 같습니다
전에 이런 것을 매직 넘버라고 표현하며 좋지 않다고 지적을 받은 적이 있습니다

에러코드와 같은 것은 축약을 하는 가치가 있지만 지금 위에서 보여주는 정도는 Enum 을 활용하는 것으로 충분할 것 같습니다

**Comment by Hyune-c** [comment]
- 한번에 내려가는 정보가 너무 많은 것이 아닌가 싶습니다
  - 지금 만드신 형태를 분리하면 battingResult 를 만들고 그 결과의 필요에 따라 updatedPlayer 와 currentBaseman 를 호출할 수 있을 듯합니다
  - updatedStatus 는 inningStatus, currentScore 만 가지게 분리할 수 있어, 좀 더 client 에 자유도를 줄 수 있을 것 같습니다

**Comment by jypthemiracle** [comment]
자바지기의 "매직넘버 사용을 최대한 자제하자" 라는 논지의 글.
https://www.slipp.net/questions/356

**Comment by jypthemiracle** [comment]
아.. 확실히 이것은 내일 같이 이야기를 맞춰봐야 할 사항인 것 같네요.
저는 클라이언트가 정보를 갖고 있지 않고, 서버 요청으로 모든 것을 표시할 수 있도록 하는 것이 좋지 않나라고 생각했습니다. 클라이언트는 현재 접속한 사용자의 정보만 알고 있고, View의 역할만 하는 것이지요. 어디까지는 클라이언트가 정보를 가지고 있어야 하고, 어디까지 서버가 정보를 제공해주어야 할 지 추가 논의가 필요합니다.

의견을 반영하여 다음과 같이 수정해보았습니다.
주요한 수정사항은 다음과 같습니다.
* 매직넘버의 사용을 자제하기 위하여 홈 팀과 어웨이 팀이라는 개념을 도입하였습니다.
	* teamType으로 Enum 타입으로 선언하여 홈과 어웨이로 지정하면 좋지 않을까 합니다.
```
{
  "currentPlayer": [
  	[
  		"id": 0,
  		"name": "Dan",
  		"type": "Pitcher",
    	"teamType": "Home",
    	"name": "SK Wyverns"
		],
  	[
    	"id": 2,
    	"name": "Sigrid",
    	"type": "Batter",
    	"teamType": "Away",
    	"name": "Doosan Bears"
	],
	"currentStatus": [
  		"inningStatus": [
  			"inningNum": 1,
  			"inningType": "초", //HomeTeam은 무조건 초에 공격, AwayTeam은 말에 공격
  			"strike": 1,
  			"ball": 2,
  			"out": 2
			],
			"currentBaseman": [
				"1B": [
						"playerName": "Aurora",
						"playerNum": 2
    			],
				"2B": [
						"playerName": "Amanda Tenjford",
						"playerNum": 3
    			],
				"3B": [
						"playerName": null, //현재 3루에 타자가 진출하지 않았다는 의미
						"playerNum": null
				]
			],
			"currentScore": [
				"Home": 1, //homeTeam은 인덱스가 0
				"Away": 2 //awayTeam은 인덱스가 1
			]
	]
}
```

**Comment by jypthemiracle** [comment]
{
  "playingStatus": "BALL",
  "currentPlayer": [
  	[
  		"id": 0,
  		"name": "Dan",
  		"type": "Pitcher",
    	"teamType": "Home",
    	"name": "SK Wyverns"
		],
  	[
    	"id": 2,
    	"name": "Sigrid",
    	"type": "Batter",
    	"teamType": "Away",
    	"name": "Doosan Bears"
	],
  	"inningStatus": [
  		"inningNum": 1,
  		"inningType": "초", //HomeTeam은 무조건 초에 공격, AwayTeam은 말에 공격
  		"strike": 1,
  		"ball": 2,
  		"out": 2
		],
	"currentBaseman": [
		"1B": [
				"playerName": "Aurora",
				"playerNum": 2
    	],
		"2B": [
				"playerName": "Amanda Tenjford",
				"playerNum": 3
    	],
		"3B": [
				"playerName": null, //현재 3루에 타자가 진출하지 않았다는 의미
				"playerNum": null
		],
	"currentScore": [
		"Home": 1, //homeTeam은 인덱스가 0
		"Away": 2 //awayTeam은 인덱스가 1
	]
}

**Comment by jypthemiracle** [comment]
저기서 updated...수식어가 붙인 경우는, 한 타석 이후의 상태를 나타내는 정보입니다.
예) 타석 플레이 요청에 따라 playingStatus가 볼이 나왔습니다. updatedBaseman은 그 다음 타석의 플레이하는 선수의 정보를 보여줍니다. 이전 타석과 다음 타석의 선수나 점수, 또는 루수 정보가 바뀔 수도 있고, 안 바뀔 수도 있습니다. 그저 모든 것을 던져드리기 위한 의도입니다.

**Comment by TTOzzi** [comment]
오.. 이 이슈는 못봤었는데 제가 생각했던 데이터랑 거의 일치하네요!
여기서 updatePlayer 에 투수는 현재 게임동안 던진 총 투구 수, 타자는 몇번째 타석인지와 총 안타 갯수만 추가해주시면 될 것 같아요.

**Comment by TTOzzi** [comment]
아 그리고 현재 타석의 로그도 함께 보내주실 수 있나요?
<img width="269" alt="스크린샷 2020-05-07 오후 12 03 17" src="https://user-images.githubusercontent.com/50410213/81249949-d13b4400-905a-11ea-8185-7b0fc1f0a021.png">
원래 이 로그는 제가 처리하려 했는데 어제 마스터가 멀티플레이 게임이라고 하셔서 공격일 경우 제가 주기적으로 서버에 요청을 보내더라도 상대방이 Pitch 버튼을 빠르게 연속해서 누른다면 정보가 띄엄띄엄 와서 완전하게 기록을 못할 것 같아서요.
형식은 (투구결과)(그때의 SB 카운트) 가 담긴 배열이면 될 것 같아요.

**Comment by jypthemiracle** [comment]
@TTOzzi 위의 JSON 형식 중 다음 노드에서 파악할 수 있을 것으로 생각합니다. 한번 확인해주세요.
```
"inningStatus": [
  	"inningNum": 1,
  	"inningType": "초", //HomeTeam은 무조건 초에 공격, AwayTeam은 말에 공격
  	"strike": 1,
  	"ball": 2,
  	"out": 2
	],
```

**Comment by TTOzzi** [comment]
@jypthemiracle 필요한 정보가 현재 타석에 있는 타자가 지금 진행 중인 타석의 스트라이크, 볼 기록인데 말씀해주신 노드에서는 요청한 시점의 기록밖에 알지 못합니다.
만약 공격인 상황에서 제가 1초마다 주기적으로 요청을 보내 데이터를 리로드하도록 해준다고 했을 때 상대방이 Pitch 버튼을 누르는 간격이 1초 이상이라면 받아온 응답의 inningStatus 로 제가 따로 로그를 기록하면 됩니다.
하지만 요청을 한번 보내고 받아오는 사이에 상대방이 Pitch 버튼을 2번 누른다면 1번을 건너뛴 정보를 받게 되어 로그에 구멍이 생기게 될겁니다.
제가 글을 잘 못써서 이해가 되실지 모르겠네요 ㅠ

**Comment by TTOzzi** [comment]
@jypthemiracle 작성하다 보니 멀티 플레이에서 공격인 경우엔 공을 안던지고 데이터 새로고침만 할 테니 JSON 데이터의 양식은 같지만 공을 던지는 로직이 빠진 가장 최근 데이터만 받아오는 요청이 따로 있어야 할 것 같아요.
전엔 컴퓨터와 플레이한다고 생각해서 Pitch 버튼을 누르는 수비인 상황과 공격인 상황의 요청이 같았지만 멀티플레이라면 조금 달라지겠네요.

**Comment by jypthemiracle** [comment]
@TTOzzi 가장 최근의 데이터를 가져오는 API 요청이 필요하다는 말씀이시겠네요.
이는, 위의 양식에서 공을 던지고 이에 따른 타자의 결과를 반환하는 결과만 제외하면 될 것 같습니다.
아래는 예시이며 참고 부탁드립니다.
```
"inningStatus": [
  	"inningNum": 1,
  	"inningType": "초", //HomeTeam은 무조건 초에 공격, AwayTeam은 말에 공격
  	"strike": 1,
  	"ball": 2,
  	"out": 2
	],
  "updatedBaseman": [
	"1B": [
			"name": "Aurora",
			"id": 2
    ],
	"2B": [
			"name": "Amanda Tenjford",
			"id": 3
    ],
	"3B": [
			"name": null, //현재 3루에 타자가 진출하지 않았다는 의미
			"id": null
	],
	"updatedScore": [
		"Home": 1, //homeTeam은 인덱스가 0
		"Away": 2 //awayTeam은 인덱스가 1
	],
	"updatedPlayer": [
  		[
  			"id": 0,
  			"name": "Dan",
  			"type": "Pitcher",
    		"teamType": "Home",
    		"name": "SK Wyverns"
		],
  		[
    		"id": 2,
    		"name": "Sigrid",
    		"type": "Batter",
    		"teamType": "Away",
    		"name": "Doosan Bears"
		]
	]
```

**Comment by jypthemiracle** [comment]
@TTOzzi 질문이 있습니다.
만약 저렇게 나눈다고 한다면, 공을 던지는 API와 최신 정보를 가져오는 API를 분리하게 됩니다.
그러한 경우에는, 굳이 공을 던지는 API의 반환 값으로 최신 정보를 반환하는 것이 필요할까요?

**Comment by jypthemiracle** [comment]
@Ellin 님께서 팀 이름과 팀 점수를 함께 제공해달라는 요청을 해 주셨습니다.
백엔드 측에서는 프론트엔드가 처음에 팀을 선택할 때 팀 이름을 반환하기 떄문에, 이를 변수로서 사용할 수 있을 것이라고 답변하였습니다. 만약 모두 필요하다고 하시면 API를 던져드릴 수 있습니다.

**Comment by TTOzzi** [comment]
@jypthemiracle 말씀하신 것처럼 공을 던지는 경우는 공을 던지는 결과값만 반환해주고 최신 정보를 가져오는 API 에서 데이터를 받아오는 게 더 좋은 것 같네요!
아까 말씀드렸던 타석 로그 부분은 백엔드에서 배열로 반환해주시는 방법도 있지만 프론트와 맞춰서 버튼에 쿨타임? 을 주는 방법도 있을 것 같긴 해요.

**Comment by jypthemiracle** [comment]
음.. 타석 로그는 배열로 반환을 해주긴 해야 할 것 같구요.
이와 별개로 쿨타임을 서로 맞추시는 것도 방법이겠네요.
또는 쿨타임 시간에 서버가 "쿨타임이므로 갱신할 수 없다는" 메시지를 줘도 좋을 것 같네요.

**Comment by TTOzzi** [comment]
`쿨타임 시간에 서버가 "쿨타임이므로 갱신할 수 없다는" 메시지를 줘도 좋을 것 같네요.`
오 이 방법도 가능하다면 좋은 방법인 것 같아요. 서버에서 처리해주면 두 클라이언트 쿨타임이 잘못 맞물리는 경우는 없을 테니까요.
그렇지만 이렇게 되면 백엔드에서 너무 많은 일을 하시는 것 같아요.
저는 배열로 반환받더라도 버튼 클릭 후 `요청 -> 응답 -> 뷰 업데이트` 동안은 버튼을 비활성화 해놓을 거라 자체적으로 어느 정도의 쿨타임은 생길 거에요. 로그를 배열로 반환해주신다면 굳이 서버에서까지 쿨타임을 줄 필요는 없을 것 같아요!

**Comment by jypthemiracle** [comment]
네. 그러면 로그는 배열로 반환하고, 쿨타임은 서버에서 제공하지는 않겠습니다.
단, @Elllin 과 상호 협의가 잘 이루어지기만 하면 좋을 것 같네요. :)

로그를 배열로 반환하는 예시 형식은 다음과 같습니다. 위에서 토의한 형식과 차이는 없습니다.
```
"inningStatus": [
  	"inningNum": 1,
  	"inningType": "초", //HomeTeam은 무조건 초에 공격, AwayTeam은 말에 공격
  	"strike": 1,
  	"ball": 2,
  	"out": 2
	],
```

**Comment by TTOzzi** [comment]
@jypthemiracle 
<img width="269" alt="스크린샷 2020-05-07 오후 12 03 17" src="https://user-images.githubusercontent.com/50410213/81271084-9a7b2300-9086-11ea-86b8-e194f1a56f3b.png">
앗 여기서의 로그는 현재 타석의 로그라 inningStatus 형식과는 조금 다릅니다.
strike 와 ball 정보만 있음 되겠네요.

**Comment by jypthemiracle** [comment]
@TTOzzi 확인했습니다. 즉, 현재 타자의 타구 정보를 가져오는 API가 필요하다는 말씀이시겠네요.

다음과 같이 제공하겠습니다.
1) 투구에 대한 배팅 결과(STRIKE, BALL, OUT, END, HIT, PROCEED)
* ```PROCEED```는 포볼에 대한 진루를 의미함
2) 1번의 결과가 반영된 이닝 결과를 보여줍니다. 새로운 투구가 시작되기 직전의 상황을 보여줍니다.
* 점수, 현재 타자 정보, 현재 투수 정보 등
